'use client';
import {useEffect,useState} from 'react';
import {Search,Check,Save} from 'lucide-react';
import {useRouter} from 'next/navigation';
import Nav from '@/components/layout/Nav';
import {createClient} from '@/lib/supabase/client';
import {money} from '@/lib/format';
import type {AppRole} from '@/lib/auth';

type Row={id:string;name:string;price?:number;sale_price?:number;cost_price?:number;unit?:string;category?:string};
export default function PriceEditor({kind,name,role}:{kind:'dishes'|'ingredients';name:string;role:AppRole}){
  const[rows,setRows]=useState<Row[]>([]),[drafts,setDrafts]=useState<Record<string,string>>({}),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState<string[]>([]),[status,setStatus]=useState<Record<string,string>>({});
  const router=useRouter();const dishes=kind==='dishes';
  useEffect(()=>{let alive=true;async function load(){try{const sb=createClient();const{data,error}=await sb.from(kind).select('*').order('name');if(error)throw error;if(alive)setRows(data||[])}catch(e){if(alive){const message=typeof e==='object'&&e&&'message' in e?String((e as {message?:unknown}).message||''):'';setError(message?`Не удалось загрузить данные: ${message}`:'Не удалось загрузить цены. Обновите страницу.')}}finally{if(alive)setLoading(false)}}load();return()=>{alive=false}},[kind]);
  async function save(row:Row){const field=dishes?'sale_price':'price';const raw=drafts[row.id]??String(row[field]);const value=Number(raw.replace(',','.'));if(!raw.trim()||!Number.isFinite(value)||value<0||value>9999999999.99){setStatus(s=>({...s,[row.id]:'Введите цену от 0 до 9 999 999 999,99'}));return}setSaving(s=>[...s,row.id]);setStatus(s=>({...s,[row.id]:''}));try{const res=await fetch('/api/prices',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({kind,id:row.id,price:value})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Ошибка сохранения');setRows(rs=>rs.map(r=>r.id===row.id?{...r,[field]:data.price}:r));setDrafts(d=>({...d,[row.id]:String(data.price)}));setStatus(s=>({...s,[row.id]:'Сохранено'}));router.refresh()}catch(e){setStatus(s=>({...s,[row.id]:e instanceof Error?e.message:'Нет связи с сервером'}))}finally{setSaving(s=>s.filter(id=>id!==row.id))}}
  const filtered=rows.filter(r=>r.name.toLowerCase().includes(q.toLowerCase()));
  return <main className="shell"><Nav name={name} role={role}/><div className="toolbar"><div><div className="eyebrow">{dishes?'IL MENÙ · МЕНЮ':'LA DISPENSA · КЛАДОВАЯ'}</div><h1 className="pageTitle">{dishes?'Блюда и цены':'Ингредиенты'}</h1><p className="sub">{dishes?'Вкус остаётся любимым. Цены — под вашим контролем.':'Всё хорошее начинается с хороших продуктов.'}</p></div><label className="searchBox"><Search size={18}/><input aria-label="Поиск по названию" placeholder="Поиск по названию…" value={q} onChange={e=>setQ(e.target.value)}/></label></div><div className="notice">{dishes?'Новая цена применяется к следующим заказам. Оформленные чеки сохраняют прежние суммы.':'Цена указана за единицу ингредиента. После сохранения себестоимость блюд пересчитывается автоматически.'}</div>{error&&<p className="error" role="alert">{error}</p>}<div className="panel tableWrap"><table className="table"><thead><tr><th>{dishes?'Блюдо':'Продукт'}</th><th>{dishes?'Категория':'Единица'}</th>{dishes&&<th>Себестоимость</th>}<th>Цена, USD ($)</th><th>Изменения</th></tr></thead><tbody>{filtered.map(r=>{const field=dishes?'sale_price':'price';const dirty=drafts[r.id]!==undefined&&drafts[r.id]!==String(r[field]);return <tr key={r.id}><td><b>{r.name}</b></td><td>{dishes?r.category:r.unit}</td>{dishes&&<td>{money(r.cost_price||0)}</td>}<td><input className="search" aria-label={`Цена: ${r.name}`} inputMode="decimal" value={drafts[r.id]??String(r[field])} onChange={e=>{setDrafts(d=>({...d,[r.id]:e.target.value}));setStatus(s=>({...s,[r.id]:''}))}} disabled={saving.includes(r.id)}/></td><td><button className="pill" disabled={!dirty||saving.includes(r.id)} onClick={()=>save(r)}>{saving.includes(r.id)?'Сохраняем…':status[r.id]==='Сохранено'?<><Check size={13}/> Сохранено</>:<><Save size={13}/> Сохранить</>}</button><span role="status" className={'status '+(status[r.id]==='Сохранено'?'success':'')}>{status[r.id]}</span></td></tr>})}</tbody></table>{loading?<div className="emptyState">Загружаем цены…</div>:!filtered.length&&<div className="emptyState">{rows.length?'По вашему запросу ничего не найдено.':'Пока нет позиций.'}</div>}</div></main>
}
